export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Primary: Vibrant Purple
        primary: '#7c3aed',
        'primary-light': '#a78bfa',
        'primary-dark': '#5b21b6',
        
        // Secondary: Indigo
        secondary: '#6366f1',
        'secondary-light': '#818cf8',
        'secondary-dark': '#4338ca',
        
        // Accent: Cyan
        accent: '#06b6d4',
        'accent-light': '#22d3ee',
        'accent-dark': '#0891b2',
        
        // Neutral: Modern grays
        'dark-bg': '#0f172a',
        'dark-surface': '#1e293b',
        'dark-surface-alt': '#334155',
        
        // Light mode colors
        'light-bg': '#f8fafc',
        'light-surface': '#ffffff',
        'light-surface-alt': '#f1f5f9',
        'light-text': '#1e293b',
        'light-text-secondary': '#64748b',
        
        // Dark mode colors
        'dark-text': '#f8fafc',
        'dark-text-secondary': '#cbd5e1',
        
        // Legacy colors (kept for compatibility)
        'surface-tint': '#8319da',
        'tertiary-fixed-dim': '#fa7c8c',
        tertiary: '#a03648',
        'secondary-fixed': '#f1c1ff',
        'on-tertiary-fixed-variant': '#711228',
        'on-background': '#1e293b',
        'primary-dim': '#7500c8',
        'on-secondary-fixed': '#550e71',
        'secondary-fixed-dim': '#eaaeff',
        'on-primary-fixed-variant': '#430077',
        'tertiary-dim': '#902a3d',
        'error-dim': '#a70138',
        'inverse-on-surface': '#b392bc',
        'on-primary-container': '#360061',
        'primary-fixed': '#c285ff',
        'inverse-surface': '#1b0425',
        'inverse-primary': '#b66dff',
        'on-tertiary-fixed': '#39000d',
        outline: '#8b6c94',
        'error-container': '#f74b6d',
        'on-error-container': '#510017',
        'on-secondary-fixed-variant': '#753390',
        'on-tertiary': '#ffefef',
        background: '#faf8fc',
        error: '#b41340',
        'on-error': '#ffefef',
        'secondary-dim': '#74318f',
        'on-secondary': '#ffedff',
        'tertiary-fixed': '#ff909d',
        'primary-fixed-dim': '#b871ff',
        'on-primary-fixed': '#000000',
        'surface-bright': '#ffffff',
        'surface-variant': '#f6d0ff',
        'primary-container': '#c285ff',
        'on-primary': '#fbefff',
        'on-surface': '#1e293b',
        'on-surface-variant': '#64748b',
        surface: '#ffffff',
        'surface-container-low': '#fdf7ff',
        'surface-container': '#faf2ff',
        'surface-container-high': '#f5ebff',
        'surface-container-highest': '#ede5f7',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#f0c1ff',
        'on-secondary-container': '#5a1e7a',
        'tertiary-container': '#ff909d',
        'on-tertiary-container': '#650620',
        'outline-variant': '#d9c3e0',
        primaryDark: '#8B7CF6',
        bg: '#faf8fc',
        surface2: '#1a1320',
        muted: '#9a92b0',
        gold: '#F5A623',
        teal: '#4ECDC4',
      },
      spacing: {
        '4.5': '1.125rem',
        '5.5': '1.375rem',
        18: '4.5rem',
        22: '5.5rem',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        base: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'base': '0 2px 4px 0 rgba(0, 0, 0, 0.08)',
        'md': '0 4px 12px 0 rgba(0, 0, 0, 0.12)',
        'lg': '0 8px 24px 0 rgba(0, 0, 0, 0.15)',
        'xl': '0 12px 32px 0 rgba(0, 0, 0, 0.2)',
        'dark-sm': '0 1px 3px 0 rgba(0, 0, 0, 0.3)',
        'dark-md': '0 4px 16px 0 rgba(0, 0, 0, 0.4)',
        'dark-lg': '0 8px 32px 0 rgba(0, 0, 0, 0.5)',
      },
    },
  },
  plugins: [],
}