export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#8319da',
        'tertiary-fixed-dim': '#fa7c8c',
        tertiary: '#a03648',
        'secondary-fixed': '#f1c1ff',
        'on-tertiary-fixed-variant': '#711228',
        'on-background': '#3e2548',
        'primary-dim': '#7500c8',
        'on-secondary-fixed': '#550e71',
        secondary: '#813e9c',
        'secondary-fixed-dim': '#eaaeff',
        'on-primary-fixed-variant': '#430077',
        'tertiary-dim': '#902a3d',
        'error-dim': '#a70138',
        'inverse-on-surface': '#b392bc',
        'on-primary-container': '#360061',
        'primary-fixed': '#c285ff',
        'inverse-surface': '#1b0425',
        'inverse-primary': '#b66dff',
        'on-tertiary-fixed': '#39000d',
        outline: '#8b6c94',
        'error-container': '#f74b6d',
        'on-error-container': '#510017',
        'on-secondary-fixed-variant': '#753390',
        'on-tertiary': '#ffefef',
        background: '#fff3fd',
        error: '#b41340',
        'on-error': '#ffefef',
        'secondary-dim': '#74318f',
        'on-secondary': '#ffedff',
        'tertiary-fixed': '#ff909d',
        'primary-fixed-dim': '#b871ff',
        'on-primary-fixed': '#000000',
        'surface-bright': '#fff3fd',
        'surface-variant': '#f6d0ff',
        primary: '#8319da',
        'primary-container': '#c285ff',
        'on-primary': '#fbefff',
        'on-surface': '#3e2548',
        'on-surface-variant': '#6e5177',
        surface: '#fff3fd',
        'surface-container-low': '#feebff',
        'surface-container': '#fbe0ff',
        'surface-container-high': '#f8d8ff',
        'surface-container-highest': '#f6d0ff',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#f1c1ff',
        'on-secondary-container': '#6a2886',
        'tertiary-container': '#ff909d',
        'on-tertiary-container': '#650620',
        'outline-variant': '#c3a2cd',
        primaryDark: '#8B7CF6',
        bg:          '#fff3fd',
        surface2:    '#242235',
        muted:       '#A09DB5',
        gold:        '#F5A623',
        teal:        '#4ECDC4',
      },
    },
  },
  plugins: [],
}